#=============================================================================
# RUFF
# =============================================================================
[tool.ruff]
line-length = 200
ignore = ["E722"]
# =============================================================================
# MYPY
# =============================================================================
[tool.mypy]
python_version = '3.10'
warn_return_any = true
warn_unused_configs = true
exclude = "scratch/*"

[[tool.mypy.overrides]]
module = ["pyspark.*", "schedule"]
ignore_missing_imports = true

# =============================================================================
# PYLINT
# =============================================================================
[tool.pylint]
disable = [
    "W0621",
    "C0123",
    "C0301",
    "C0103",
    "E0611",
    "I1101",
    "R0902",
    "R0904",
    "W0201",
    "W0106",
    "W0702",
    "W0719",
]
[tool.pylint.main]
ignore = ["scratch/*"]
max-line-length = 200

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
